### ISSUE TITLE
Error with Nix 2.8

### ISSUE THREAD

**Issue by madonius** [gvolpe/falsisign.nix#3] opened 2022-06-29 21:35 UTC
Running
```
$ > nix run flake.nix#signdiv /tmp/falsisign/Signature_guide.pdf 
```
yields
```
path '/tmp/falsisign.nix/flake.nix' does not contain a 'flake.nix', searching up
error: attribute 'apps.x86_64-linux.signdiv' should have type 'app'
```

**Comment by gvolpe** [comment] 2022-06-30 08:12
Seems to be a duplicate of #1 ?

**Comment by madonius** [comment] 2022-06-30 09:03
@gvolpe no, as this is related to signdiv. I did not manage to fix it, unfortunately

**Comment by gvolpe** [comment] 2022-06-30 09:07
Weird, the error message seems to suggest it should be fixed by #2

**Comment by madonius** [comment] 2022-06-30 09:10
Unfortunately it does not. I will have a look at it later in the day

**Comment by madonius** [comment] 2022-07-04 06:54
As you might have guessed, I _forgot_ about it 
I will have a look today

**Comment by gvolpe** [comment] 2022-07-04 09:38
No worries, there's no rush :)

**Closed as completed** 2022-07-15 10:52 UTC
